### ISSUE TITLE
Be explicit that alg deprecation is the responsibility of the verifier

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#34]
Add to draft?
Revocation should/must only be used for the traditional reasons. It should/must not be used for algorithm-wide revocation because that really ought to be a policy decision on the part of the verifier.

**Comment by csosto-pk** [comment]
I think this is redundant. Entities already do this. If you don't trust a SHA-1 cert and you are a browsers you don't open the website for example. I think we could add a paragraph in the Security considerations section to talk about different algorithms though and what the verifier should do based on what he trusts. That is slightly different compared to what we do today because we only have one algorithm, but it is covered in the #sec-comp-sig-verify section, so we are good. 

The sec-alg-revocation-policy should be updated though to reflect why we chose to go that route, instead of keep old text that we had that serves no special purpose.
