### ISSUE TITLE
OID naming convention: "id-pk-compositePrivateKey" vs "id-ce-compositePrivateKey" ?

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#45]
I have no idea what the "id-ce" or "id-pk" stand for. Can someone enlighten me?

**Comment by danvangeest** [comment]
I think you mean CompositePublicKey not CompositePrivateKey? (actually it could apply to both, but I don't think `id-CompositePrivateKey` needs to be a thing, see way down in this comment)

"id-ce" is for certificate extensions so wouldn't apply here.

I don't think "id-pk" is a thing.

If we look at two of the more recent RFCs or drafts to define new algorithms for use in PKIX-related standards we have:
https://tools.ietf.org/html/draft-ietf-lamps-cms-hash-sig-08
```
   --
   -- Object Identifiers
   --
   id-alg-hss-lms-hashsig OBJECT IDENTIFIER ::= { iso(1)
       member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs9(9)
       smime(16) alg(3) 17 }

   --
   -- Signature Algorithm and Public Key
   --

   sa-HSS-LMS-HashSig SIGNATURE-ALGORITHM ::= {
       IDENTIFIER id-alg-hss-lms-hashsig
       PARAMS ARE absent
       PUBLIC-KEYS { pk-HSS-LMS-HashSig }
       SMIME-CAPS { IDENTIFIED BY id-alg-hss-lms-hashsig } }

   pk-HSS-LMS-HashSig PUBLIC-KEY ::= {
       IDENTIFIER id-alg-hss-lms-hashsig
       KEY HSS-LMS-HashSig-PublicKey
       PARAMS ARE absent
       CERT-KEY-USAGE
           { digitalSignature, nonRepudiation, keyCertSign, cRLSign } }
```

and

https://tools.ietf.org/html/rfc8410
```
   id-X25519        OBJECT IDENTIFIER ::= { id-edwards-curve-algs 110 }
   id-Ed25519       OBJECT IDENTIFIER ::= { id-edwards-curve-algs 112 }

    sa-Ed25519 SIGNATURE-ALGORITHM ::= {
       IDENTIFIER id-Ed25519
        PARAMS ARE absent
        PUBLIC-KEYS {pk-Ed25519}
        SMIME-CAPS { IDENTIFIED BY id-Ed25519 }
    }

    pk-Ed25519 PUBLIC-KEY ::= {
        IDENTIFIER id-Ed25519
        -- KEY no ASN.1 wrapping --
        PARAMS ARE absent
        CERT-KEY-USAGE {digitalSignature, nonRepudiation,
                        keyCertSign, cRLSign}
        PRIVATE-KEY CurvePrivateKey
    }
```

So for the OIDs I'd pick `id-CompositePublicKey` (or `id-alg-compositePublicKey` if you want to be more like HSS).

And I think our draft's definition of composite Signature Algorithm and Public Key corresponding to RFC 5911 would be:
```
   sa-CompositeSignature SIGNATURE-ALGORITHM ::= {
       IDENTIFIER id-CompositePublicKey
       VALUE CompositeSignatureValue
       PARAMS TYPE CompositeSignatureAlgorithmParams ARE required
       PUBLIC-KEYS { pk-CompositePublicKey }
       SMIME-CAPS { IDENTIFIED BY id-CompositePublicKey } }

CompositeSignatureAlgorithmParams ::= SEQUENCE OF AlgorithmIdentifier

CompositeSignatureValue ::= SEQUENCE OF BIT STRING

   pk-CompositePublicKey PUBLIC-KEY ::= {
       IDENTIFIER id-CompositePublicKey
       KEY CompositePublicKey
       PARAMS ARE absent
       CERT-KEY-USAGE
           { digitalSignature, nonRepudiation, keyCertSign, cRLSign }
       PRIVATE-KEY CompositePrivateKey
   }

CompositePublicKey ::= SEQUENCE OF SubjectPublicKeyInfo

CompositePrivateKey ::= SEQUENCE OF OneAsymmetricKey
```

I actually wonder if `CompositeSignatureAlgorithmParams` should be renamed `CompositeAlgorithmParams` and the same `SEQUENCE OF AlgorithmIdentifier`s be used as the params of the public key as well.  And then `CompositePublicKey ::= SEQUENCE OF SubjectPublicKeyInfo` would change to `CompositePublicKey ::= SEQUENCE OF BIT STRING`.

Pros:
- The Signature Algorithm and Public Key definitions are consistent with each other.
- The X.509 `signatureAlgorithm` field would contain meaningful information (the list of actual algorithms rather than just "Composite Thing" without an indication of the components).  And actually, it's pretty important that the `signatureAlgorithm` field contains meaningful information because this field is signed and having the actual algorithm identifiers in there will help protect against an algorithm substitution attack.
- Related to the previous point, the CMS SignerInfo.signatureAlgorithm field would then contain information on the actual component algorithms, allowing the CMS Algorithm Identifier Protection Attribute of https://tools.ietf.org/html/rfc6211 to be effective.

Cons:
- Keeping it as a sequence of `SubjectPublicKeyInfo` might work better with code which is expecting a `SubjectPublicKeyInfo` to be passed around.

Bad Compromise?: duplicate the component parameters in both the `PUBLIC-KEY` parameters and the `CompositePublicKey` as a sequence of `SubjectPublicKeyInfo`s?


And while I'm ranting, I think the `id-CompositeSignature` and `id-CompositePrivateKey` OIDs aren't necessary.

Signature OIDs only need to be defined when combined with a pre-hash algorithm (e.g. `ecdsa-with-sha384`), but a composite signature isn't combined with a pre-hash algorithm but rather each component signature may use a different (or no) pre-hash algorithm (e.g. ecdsa-with-sha384 + HSS).  EdDSA and HSS don't define different OIDs for the signature algorithm for the same reason that they don't have a pre-hash applied before the signature.

I'm not aware of any algorithms where a separate OID is defined for a private key version of the algorithm, it just uses the same public key OID (in fact I just added a definition of `CompositePrivateKey` used in `pk-CompositePublicKey` defined above which I think covers defining a composite private key using a single composite public key OID).

**Comment by ounsworth** [comment]
Discussion of PublicKey format has been split out into #59
