### ISSUE TITLE
Restructure and simplify the Public Key ASN.1

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-composite-sigs#59]
Based on feedback from Santosh Chokhani, the idea came up to restructure the Public Key ASN.1 as follows, which we believe is a simplification, and would bring it closer to the structure that @danvangeest has defined for SignatureAlgorithm:

> ```
> id-ce-compositePublicKey OBJECT IDENTIFIER ::= { OID }
> ```
> The parameters field for this public key type MUST contain a SEQUENCE of AlgorithmIdentifier (NEED TO DEFINE ASN.1, SAME ORDER AS PUBKEYS, ETC). The composite public key data is represented by the following structure:
>
> ```
> CompositePublicKey ::= SEQUENCE OF BIT STRING
> ```
> where each element is encoded according to its algorithm specification.

-----
For reference, the current text says:

> ```
> id-ce-compositePublicKey OBJECT IDENTIFIER ::= { OID }
> ```
> The parameters field for this public key type MUST be absent.  The composite public key data is represented by the following structure:
> ```
> CompositePublicKey ::= SEQUENCE OF SubjectPublicKeyInfo
> ```
>   where each element of the sequence is a "SubjectPublicKeyInfo" of a component public key.

**Comment by danvangeest** [comment]
This is the second point that I was trying to make on issue #45:

> I actually wonder if CompositeSignatureAlgorithmParams should be renamed CompositeAlgorithmParams and the same SEQUENCE OF AlgorithmIdentifiers be used as the params of the public key as well. And then CompositePublicKey ::= SEQUENCE OF SubjectPublicKeyInfo would change to CompositePublicKey ::= SEQUENCE OF BIT STRING.
> 
> Pros:
> 
> - The Signature Algorithm and Public Key definitions are consistent with each other.
> - The X.509 signatureAlgorithm field would contain meaningful information (the list of actual algorithms rather than just "Composite Thing" without an indication of the components). And actually, it's pretty important that the signatureAlgorithm field contains meaningful information because this field is signed and having the actual algorithm identifiers in there will help protect against an algorithm substitution attack.
> - Related to the previous point, the CMS SignerInfo.signatureAlgorithm field would then contain information on the actual component algorithms, allowing the CMS Algorithm Identifier Protection Attribute of https://tools.ietf.org/html/rfc6211 to be effective.
> 
> Cons:
> 
> - Keeping it as a sequence of SubjectPublicKeyInfo might work better with code which is expecting a SubjectPublicKeyInfo to be passed around.
> 
> Bad Compromise?: duplicate the component parameters in both the PUBLIC-KEY parameters and the CompositePublicKey as a sequence of SubjectPublicKeyInfos?

My pro statements for "the X.509 signatureAlgorithm field" and "the CMS SignerInfo.signatureAlgorithm field" might not actually matter.  We put a `CompositeParams` object in the params field of the AlgorithmIdentifier in the X.509/CMS signature field, so the signature will cover the OIDs of the components.

**Comment by ounsworth** [comment]
Heh, clearly I hadn't fully digested your comments on #45 

Let's discuss on the call, but seems like you, Serge, and I are in agreement that this would be a benificial change.

**Comment by danvangeest** [comment]
I haven't gotten to implementing verification yet, but when I do I'll see if "Keeping it as a sequence of SubjectPublicKeyInfo might work better with code which is expecting a SubjectPublicKeyInfo to be passed around." applies in a sample of 1.

**Comment by ounsworth** [comment]
Yeah, let us know what you find.

I suspect that which option is "least disruptive to existing APIs" is going to depend on which library you're talking about. For example, the signVerify operation in Java / JCA [looks like this](https://docs.oracle.com/javase/9/security/java-cryptography-architecture-jca-reference-guide.htm#GUID-7389E94B-A595-4020-A4D2-73FB0DD5A05A):

```
Signature dsa = Signature.getInstance("SHA256withDSA");

/* Initializing the object with the public key */
PublicKey pub = pair.getPublic();
dsa.initVerify(pub);

/* Update and verify the data */
dsa.update(data);
boolean verifies = dsa.verify(sig);
```

I assume that either approach would be equivalent in that the `PublicKey` object already contains the full SubjectPublicKeyInfo, containing both the AlgID+Params, and the public key itself, therefore `Signature.verify(..)` when called on a Composite type, will have all the information it needs to call the correct sub-verify's.

**Comment by danvangeest** [comment]
Your Java code made me realize that signing in Java (and in general) might be more complicated with Composite sigs.
```
    Signature dsa = Signature.getInstance("SHA256withDSA");

   /* Initializing the object with a private key */
    PrivateKey priv = pair.getPrivate();
    dsa.initSign(priv);

   /* Update and sign the data */
    dsa.update(data);
    byte[] sig = dsa.sign();
```
Just replacing "SHA256withDSA" with "Composite" wouldn't work because, while the private key will contain the private keys to sign with, there's no indication which hash algorithm (if any) to use with those keys.  e.g. if the CompositeKey is { SEP521, Ed25519, Dilithium } then SECP521 can be paired with any hash algorithm, Ed25519 is not paired with any hash algorithm and Dilithium is (currently not yet defined in X.509 but pre-hashing is not necessary so I'd hope they define it to use no-pre-hashing like Ed25519).
Requesting "SHA256withComposite" doesn't make sense because there's no sha256-with-composite OID defined, and not all of the component algorithm will use a SHA256 pre-hash (and what if you wanted to use one composite key with a SHA256 pre-hash and another with SHA5-1024 or some future cutting-edge hash algorithm which isn't widely supported).

**Comment by ounsworth** [comment]
Yeah, the issue of "each component key may use a different hash function" is definitely messy -- I ran into the same problem when trying to implement this in Go.

I am assuming that the hash alg is contained inside the AlgIdParams? So I'm assuming that if you do
```
Signature dsa = Signature.getInstance("Composite");

/* Initializing the object with the public key */
PublicKey pub = pair.getPublic();
dsa.initSign(priv);
```
that will contain enough info that it can go and construct the `HASH-ALG` strings that it needs to instantiate the component algorithms.

**Comment by danvangeest** [comment]
I don't think that code will have enough info.  For example, the key pair will have been loaded from somewhere (PKCS#8 file, KeyStore, ...) but there's nothing in the PKCS#8 format that would indicate which pre-hash algorithm is used to sign/verify (nor should there be, because it could vary based on application).
Since the key pair has the public key algorithms listed (e.g. ecPublicKey), but not the signature algorithms (sha256-with-ecdsa), something will have to be be added to associate each component public/private key with the signature algorithm to be used for verifying/signing.

**Comment by ounsworth** [comment]
Interesting. 

How is that different from a traditional RSA key?

**Comment by danvangeest** [comment]
With a traditional RSA key, the PKCS#8 file/KeyStore will only indicate that that it's an RSA key, it won't have any signing info.
When the user instantiates the `Signature` object
```
Signature signature = Signature.getInstance("SHA1withRSA");
```
they specify "SHA1withRSA", so the `Signature` object knows that it will pre-hash with SHA1 before using the private key to sign the hash.
```
signature.initSign(keyPair.getPrivate());
```
associates the RSA key with the signature message, then `signature.update(message)` and `sinature.sign()` do the actual signing.

**Comment by sfluhrer** [comment]
And how does the user know to specify SHA1?

Now, if that does turn out to be a huge problem (or we need to sign large messages, and don’t want the expense of running multiple hash functions over the message), one alternative is that we could do an initial hash of the message (ideally using a better hash function that SHA1), and then have each of the component hash functions sign the hash.

On the other hand, one issue is that how does the individual signature algorithms deal with the hash; some may want to rehash it; others might want to treat it as raw data – that’s a complexity we may be better staying away from.

However, it would appear to address this issue (assuming that the user knows which outer hash we used – that would appear to be a somewhat solved problem…)

**Comment by danvangeest** [comment]
The SHA1 (or SHA256, or ...) is based on the application.  That was just example code, but if it was used to establish a TLS connection and sign the handshake then "SHA1withRSA" would be replaced with whatever was negotiated in the handshake.  If it was used by a CA to create a certificate the hash algorithm to use would be based on CA policy (or requester's suggestion?).  If it was used to verify an X.509 certificate then "SHA1withRSA" or something else would be picked after parsing the certificate's signature AlgorithmIdentifier.

If we have to do an initial hash of the message and have the components do a signature (or additional hash+signature) then we'd either have to define a hash to always use for pre-hashing, or we'd have to define new OIDs such as SHA256withComposite, SHA512withComposite, etc.  I'm not sure either is a great solution, ideally the Composite signature would be hash agnostic and would leave it up to the components, but there could be issues there as we're seeing.

**Comment by danvangeest** [comment]
For the idea of
```
CompositePublicKey ::= SEQUENCE OF SubjectPublicKeyInfo
```
vs
```
CompositePublicKey ::= SEQUENCE OF BIT STRING
```
with the component algorithm identifiers included in the composite algorithm identifier's parameters field:

In Java JCA the first option is simpler.  You have to pass an encoded SubjectPublicKeyInfo into a KeyFactory to get a usable PublicKey object.  The first option gives you the encoded `SubjectPublicKeyInfo` directly, while the second option would require you to get the OID and the public key from two separate lists and then ASN.1 encode them into a SEQUENCE yourself so it can be passed to a KeyFactory.

For what it's worth, the first option is also simpler in mbedTLS.  There's already a function to parse a `SubjectPublicKeyInfo` struct into an internal public key representation so parsing a `SEQUENCE OF SubjectPublicKeyInfo` is easy.  For the other option we would have to parse both the `SEQUENCE OF AlgorithmIdentifier` from the params and the `SEQUENCE OF BIT STRING` (one after the other, or in parallel, either way it's less clean) and inject the components into an internal public key representation.

I suspect for other implementations it will be similar because they all have to parse a `SubjectPublicKeyInfo` already to convert it to an internal public key representation, and one would hope they've abstracted that out since other places use the same encoding to define a key (e.g. CMS' `OriginatorPublicKey`).

**Comment by ounsworth** [comment]
Perfect, I propose closing this issue as "We like it the way it is".

**Comment by ounsworth** [comment]
```
SubjectPublicKeyInfo  ::=  SEQUENCE  {
    algorithm            AlgorithmIdentifier,
    subjectPublicKey     BIT STRING  }
    
Alg1: {
   algorithm={alg1, param1}
   subjectPublicKey=value1
}

Alg2: {
   algorithm={alg2, param2}
   subjectPublicKey=value2
}


Current composite:
    CompositeAlg: {
       algorithm={composite, none}
       subjectPublicKey=encoded({{alg1, param1}, value1}, {{alg2, param2}, value2})
    }

Alternative 1:
    CompositeAlg: {
       algorithm={composite, {{alg1, param1}, {alg2, param2}}
       subjectPublicKey=encoded(value1, value2)
    }

Alternative 2:
    CompositeAlg: {
       algorithm={composite, {alg1, alg2}}
       subjectPublicKey=encoded({{alg1, param1}, value1}, {{alg2, param2}, value2})
    }
```

Decision: let's keep the draft as-is for IETF105, but we need to mention this in an EDNOTE, in the presentation, and on the mailing list.
